language: node_js
cache:
  directories:
    - node_modules
node_js:
 - "node"
before_script:
  - npm prune
script:
  - npm run test:coverage
  - npm run ci:bithound
  - npm run build
after_success:
  - npm run ci:codecov
  - npm run ci:semantic-release